<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net8.0-windows10.0.19041.0</TargetFramework>
    <TargetPlatformMinVersion>10.0.19041.0</TargetPlatformMinVersion>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\OutlookNextEvent.Core\OutlookNextEvent.Core.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.Graph" Version="6.7.0" />
    <PackageReference Include="Microsoft.Identity.Client" Version="4.90.0" />
    <PackageReference Include="Microsoft.Identity.Client.Broker" Version="4.90.0" />
  </ItemGroup>
</Project>
